from bs4 import BeautifulSoup
import os

pages = {
    "agentic-commerce.html": {
        "title": "Agentic Commerce - Nexmart",
        "desc": "The core artificial intelligence engine of Nexmart deploying autonomous agents to handle product discovery, negotiation, and checkout.",
        "name": "Agentic Commerce",
        "hero_desc": "Deploy autonomous AI agents to handle the entire shopping and procurement lifecycle—from product discovery to tracking.",
        "cta1_text": "Start Shopping With AI",
        "cta1_link": "https://app.nexmartshop.ai/sign-up",
        "overview_heading": "Your AI Shopping Assistant",
        "overview_desc": "Nexmart's Agentic Commerce engine powers millions of transactions effortlessly. Let our 9 specialized AI agents work together behind the scenes, ensuring every decision maximizes value while you remain handsfree.",
        "cta2_text": "Download App",
        "cta2_link": "#TODO-APP-STORE-LINK",
        "features_heading": "Intelligent AI Agents",
        "features_sub": "Our platform deploys specialized agents for every step of the commerce lifecycle.",
        "f1_title": "Discovery Agent", "f1_desc": "Finds products matching your exact needs, preferences, and budgets across millions of listings.",
        "f2_title": "Price & Coupon Agents", "f2_desc": "Tracks prices across sellers and automatically applies discounts, promotions, and cashback.",
        "f3_title": "Negotiation Agent", "f3_desc": "Communicates directly with sellers to secure better offers and bulk pricing.",
        "f4_title": "Quality Agent", "f4_desc": "Verifies authenticity, seller reputation, and warranty information before purchase.",
        "f5_title": "Checkout Agent", "f5_desc": "Builds your cart and handles secure payment and order processing seamlessly.",
        "f6_title": "Tracking & Support", "f6_desc": "Monitors deliveries in real-time and manages returns, refunds, and exchanges.",
        "how_heading": "How Agentic Commerce Works",
        "how_sub": "Experience handsfree Nexmartping today.",
        "s1_title": "Describe Your Needs", "s1_desc": "Simply input what you want. No endless searching or comparison fatigue.",
        "s2_title": "Agents Collaborate", "s2_desc": "Our 9 AI agents discover, research, and negotiate the best possible options on your behalf.",
        "s3_title": "Automated Execution", "s3_desc": "Approve the final cart, and the system securely handles checkout and logistics tracking.",
        "use_heading": "Who Uses Agentic Commerce?",
        "use_sub": "Built to scale for diverse procurement needs.",
        "u1_title": "Everyday Consumers", "u1_ben": "Save Time & Money", "u1_desc": "Stop browsing. Let AI find better prices and execute purchases while you sleep.",
        "u2_title": "E-commerce Merchants", "u2_ben": "Automated Procurement", "u2_desc": "Use agents to identify trending products, monitor competitors, and streamline sourcing.",
        "u3_title": "Enterprise Brands", "u3_ben": "Supply Chain Efficiency", "u3_desc": "Deploy intelligent shopping agents to automate bulk procurement and optimize supplier relationships.",
        "use_cta_text": "View Related: Magic AI Search",
        "use_cta_link": "magic-ai-search.html",
        "final_heading": "Experience true Agentic Commerce today",
        "final_desc": "Save time, save money, and shop smarter. Your AI agents never sleep.",
        "final_cta_text": "Start Shopping With AI",
        "final_cta_link": "https://app.nexmartshop.ai/sign-up"
    },
    "magic-ai-search.html": {
        "title": "Magic AI Search - Nexmart",
        "desc": "A powerful multimodal search engine for discovering high-converting trends and products.",
        "name": "Magic AI Search",
        "hero_desc": "Explore our vast database of millions of products and ads using natural language queries and image visual search.",
        "cta1_text": "Try Magic AI Search",
        "cta1_link": "https://app.nexmartshop.ai/solutions/magic-ai-search",
        "overview_heading": "Find Profitable Products Faster",
        "overview_desc": "Use AI to find exactly what's trending. Simply describe what you are looking for—like 'Find me the best selling products in Europe'—and our agentic engine surfaces real-time results based on actual market data.",
        "cta2_text": "Watch Tutorial",
        "cta2_link": "https://app.nexmartshop.ai/videos/magic-ai-search",
        "features_heading": "Advanced Search Capabilities",
        "features_sub": "Discover market trends with multimodal inputs.",
        "f1_title": "Natural Language Queries", "f1_desc": "Search using conversational prompts instead of rigid keywords.",
        "f2_title": "Image-Based Search", "f2_desc": "Upload photos to visually match products and discover similar converting ads.",
        "f3_title": "Trend Discovery", "f3_desc": "Instantly see what is trending across TikTok and Facebook.",
        "f4_title": "Ad Activity Tracking", "f4_desc": "Monitor active ad campaigns related to your specific search queries.",
        "f5_title": "Real-Time Market Data", "f5_desc": "Our database updates constantly to reflect what's working right now.",
        "f6_title": "Agentic Integration", "f6_desc": "Seamlessly send discovered products to your Portfolio or tracking agents.",
        "how_heading": "How Magic AI Search Works",
        "how_sub": "Uncover winning products in three easy steps.",
        "s1_title": "Input Your Query", "s1_desc": "Type a prompt like 'Show me top earners in home decor' or upload an image.",
        "s2_title": "AI Processing", "s2_desc": "The engine scans millions of products, ads, and TikTok shops simultaneously.",
        "s3_title": "Analyze Results", "s3_desc": "Review matched products, ad spend data, and historical revenue metrics.",
        "use_heading": "Who Uses Magic AI Search?",
        "use_sub": "Essential intelligence for digital merchants.",
        "u1_title": "E-commerce Merchants", "u1_ben": "Discover Winning Products", "u1_desc": "Find untapped niches and high-converting products before the competition.",
        "u2_title": "Media Buyers", "u2_ben": "Ad Inspiration", "u2_desc": "Search for specific product ads to see what creatives are currently scaling.",
        "u3_title": "Enterprise Brands", "u3_ben": "Market Intelligence", "u3_desc": "Analyze vast amounts of market data to inform product development.",
        "use_cta_text": "View Related: Agentic Commerce",
        "use_cta_link": "agentic-commerce.html",
        "final_heading": "Ready to find your next winner?",
        "final_desc": "Stop guessing. Start searching with Agentic Commerce.",
        "final_cta_text": "Try Magic AI Search",
        "final_cta_link": "https://app.nexmartshop.ai/solutions/magic-ai-search"
    },
    "advertiser-tracker.html": {
        "title": "Advertiser Tracker - Nexmart",
        "desc": "Actively monitor specific Facebook advertisers, log new campaigns, and gain deep ad insights.",
        "name": "Advertiser Tracker",
        "hero_desc": "Track your competitors' Facebook ad strategies in real-time. Log new campaigns and monitor ad activity.",
        "cta1_text": "Start Tracking",
        "cta1_link": "https://app.nexmartshop.ai/sign-up",
        "overview_heading": "Monitor Competitor Campaigns",
        "overview_desc": "Gain an unfair advantage by actively tracking specific advertisers. Whenever your tracked competitors launch new Facebook ads, Advertiser Tracker logs them so you can dissect their creative strategy and scaling tactics.",
        "cta2_text": "Explore Ad Library",
        "cta2_link": "advertiser-library.html",
        "features_heading": "Targeted Ad Intelligence",
        "features_sub": "Everything you need to monitor competitor strategies.",
        "f1_title": "Advertiser Monitoring", "f1_desc": "Add specific Facebook advertisers to your watch list with one click.",
        "f2_title": "Campaign Logging", "f2_desc": "Automatically log and archive every new ad launched by tracked competitors.",
        "f3_title": "Creative Analysis", "f3_desc": "Review the exact creatives, copy, and calls-to-action your competitors use.",
        "f4_title": "Activity Alerts", "f4_desc": "Stay informed when competitors significantly increase their ad activity.",
        "f5_title": "Historical Ad Data", "f5_desc": "Access a chronological history of a competitor's ad strategies.",
        "f6_title": "Seamless Integration", "f6_desc": "Move insights directly into your Nexmartping product research workflow.",
        "how_heading": "How Advertiser Tracker Works",
        "how_sub": "Set up monitoring in minutes.",
        "s1_title": "Identify Competitors", "s1_desc": "Find relevant advertisers through the Advertiser Library or Competitor Research tool.",
        "s2_title": "Track with One Click", "s2_desc": "Hit the 'Track' button to add the advertiser to your dashboard.",
        "s3_title": "Monitor Activity", "s3_desc": "Review newly logged ads and campaign changes as they happen in real-time.",
        "use_heading": "Who Uses Advertiser Tracker?",
        "use_sub": "Vital for maintaining a competitive edge.",
        "u1_title": "Media Buyers", "u1_ben": "Creative Inspiration", "u1_desc": "Monitor successful brands to understand what ad formats are currently working.",
        "u2_title": "E-commerce Merchants", "u2_ben": "Strategy Dissection", "u2_desc": "Watch direct competitors closely to anticipate their product launches and sales.",
        "u3_title": "Enterprise Brands", "u3_ben": "Market Defense", "u3_desc": "Track industry leaders to ensure your marketing remains competitive.",
        "use_cta_text": "View Related: Competitor Research",
        "use_cta_link": "competitor-research.html",
        "final_heading": "Stay one step ahead of the competition.",
        "final_desc": "Start logging competitor ads today and uncover their scaling secrets.",
        "final_cta_text": "Start Tracking",
        "final_cta_link": "https://app.nexmartshop.ai/sign-up"
    },
    "advertiser-library.html": {
        "title": "Advertiser Library - Nexmart",
        "desc": "Discover and analyze advertisers across platforms, revealing actual ad spend and driving revenue.",
        "name": "Advertiser Library",
        "hero_desc": "A comprehensive database to analyze competitor ad spend in Naira and identify high-revenue campaigns.",
        "cta1_text": "Explore Ad Library",
        "cta1_link": "https://app.nexmartshop.ai/solutions/advertiser-library",
        "overview_heading": "Uncover the Biggest Spenders",
        "overview_desc": "Stop guessing what works. The Advertiser Library reveals exactly who is spending the most money on ads in your niche. Filter by category, region, and actual ad spend to find the most successful campaigns on the market.",
        "cta2_text": "Start Free Trial",
        "cta2_link": "https://app.nexmartshop.ai/sign-up",
        "features_heading": "Comprehensive Ad Analytics",
        "features_sub": "Deep insights into global ad spending.",
        "f1_title": "Actual Ad Spend Data", "f1_desc": "See total spend in Naira, not just vague campaign or adset estimates.",
        "f2_title": "Category-Level Targeting", "f2_desc": "Filter millions of ads to see only advertisers in your exact e-commerce industry.",
        "f3_title": "EU Ad Spend Filtering", "f3_desc": "Set minimum and maximum spend limits to find advertisers operating at your scale.",
        "f4_title": "Advertiser Insights", "f4_desc": "Access detailed profiles, similar ads, and underlying Facebook pages.",
        "f5_title": "Historical Analytics", "f5_desc": "View long-term spending patterns to identify seasonal trends and scaling phases.",
        "f6_title": "One-Click Tracking", "f6_desc": "Instantly send any discovered advertiser to the Advertiser Tracker.",
        "how_heading": "How to Use the Library",
        "how_sub": "Find winning ad strategies instantly.",
        "s1_title": "Search and Filter", "s1_desc": "Apply category, regional, and spend filters to narrow down the database.",
        "s2_title": "Analyze Ad Spend", "s2_desc": "Review exactly how much top competitors are investing in specific creatives.",
        "s3_title": "Extract Insights", "s3_desc": "Use these data-driven insights to optimize your own Nexmartping ad campaigns.",
        "use_heading": "Who Uses Advertiser Library?",
        "use_sub": "The ultimate tool for data-driven marketers.",
        "u1_title": "Media Buyers", "u1_ben": "Scale Confidently", "u1_desc": "See exactly which ad formats justify high ad spend before investing your own budget.",
        "u2_title": "E-commerce Merchants", "u2_ben": "Niche Discovery", "u2_desc": "Find highly profitable niches by following the money of successful advertisers.",
        "u3_title": "Enterprise Brands", "u3_ben": "Global Benchmarking", "u3_desc": "Compare your ad spend efficiency against industry leaders.",
        "use_cta_text": "View Related: Creator Library",
        "use_cta_link": "creator-library.html",
        "final_heading": "Follow the money to success.",
        "final_desc": "Access the Advertiser Library today and see what your competitors are spending.",
        "final_cta_text": "Explore Ad Library",
        "final_cta_link": "https://app.nexmartshop.ai/solutions/advertiser-library"
    },
    "portfolio.html": {
        "title": "Portfolio - Nexmart",
        "desc": "Receive a curated, weekly delivery of winning products identified by Agentic Commerce.",
        "name": "Portfolio",
        "hero_desc": "Receive weekly deliveries of high-converting, winning dropshipping products straight to your dashboard.",
        "cta1_text": "Get Weekly Products",
        "cta1_link": "https://app.nexmartshop.ai/solutions/portfolio",
        "overview_heading": "Winning Products on Autopilot",
        "overview_desc": "Say goodbye to manual product research. Portfolio leverages our advanced Agentic Commerce engine to identify untapped, high-revenue products and delivers these exclusive Nexmartping opportunities to you every single week.",
        "cta2_text": "View Example Portfolio",
        "cta2_link": "#TODO-PORTFOLIO-SHOWCASE",
        "features_heading": "Curated E-commerce Intelligence",
        "features_sub": "Let AI do the heavy lifting of product discovery.",
        "f1_title": "Weekly Product Drops", "f1_desc": "Receive fresh, vetted product opportunities delivered weekly.",
        "f2_title": "Revenue Verified", "f2_desc": "Every portfolio product is backed by real-time sales and revenue metrics.",
        "f3_title": "Handsfree Research", "f3_desc": "Our agents analyze millions of data points so you don't have to.",
        "f4_title": "Historical Trend Data", "f4_desc": "View the growth trajectory of recommended products to time your entry.",
        "f5_title": "Competitor Analysis", "f5_desc": "Understand exactly who is currently selling the product and how they market it.",
        "f6_title": "Ready for Pre-built Stores", "f6_desc": "Seamlessly integrate Portfolio winners into your generated Shopify stores.",
        "how_heading": "How Portfolio Works",
        "how_sub": "Automate your product sourcing.",
        "s1_title": "AI Discovery", "s1_desc": "Our agents constantly scan global marketplaces for rising trends and sales spikes.",
        "s2_title": "Data Verification", "s2_desc": "We verify the revenue metrics to ensure the product has genuine market demand.",
        "s3_title": "Weekly Delivery", "s3_desc": "You receive a curated dashboard of actionable products ready for your store.",
        "use_heading": "Who Uses Portfolio?",
        "use_sub": "Designed for rapid e-commerce scaling.",
        "u1_title": "E-commerce Merchants", "u1_ben": "Consistent Growth", "u1_desc": "Keep your store fresh with a steady pipeline of proven, profitable products.",
        "u2_title": "Beginner Entrepreneurs", "u2_ben": "Remove Guesswork", "u2_desc": "Start your Nexmartping journey with products that already have validated demand.",
        "u3_title": "Media Buyers", "u3_ben": "Fresh Ad Angles", "u3_desc": "Discover new product trends to test against your existing ad accounts.",
        "use_cta_text": "View Related: Pre-built Stores",
        "use_cta_link": "pre-built-stores.html",
        "final_heading": "Automate your product research.",
        "final_desc": "Start receiving winning products every week and scale your business.",
        "final_cta_text": "Get Weekly Products",
        "final_cta_link": "https://app.nexmartshop.ai/solutions/portfolio"
    },
    "creator-library.html": {
        "title": "Creator Library - Nexmart",
        "desc": "Discover TikTok creators who turn views into real shop sales using historical revenue analysis.",
        "name": "Creator Library",
        "hero_desc": "Discover TikTok creators who actually convert. Rank influencers by generated revenue, not vanity metrics.",
        "cta1_text": "Discover Creators",
        "cta1_link": "https://app.nexmartshop.ai/sign-up",
        "overview_heading": "Find Influencers Who Sell",
        "overview_desc": "Stop paying for empty views. The Creator Library connects TikTok creators directly to their shop sales data. Evaluate every video by the actual revenue it generated, ensuring you only partner with creators proven to drive e-commerce results.",
        "cta2_text": "Start Free Trial",
        "cta2_link": "https://app.nexmartshop.ai/sign-up",
        "features_heading": "Data-Driven Influencer Marketing",
        "features_sub": "Measure what matters: Sales and Revenue.",
        "f1_title": "Revenue-Ranked Creators", "f1_desc": "See which creators turn views into real TikTok Shop sales.",
        "f2_title": "Full Creator History", "f2_desc": "Access complete histories of sales, revenue, videos, linked shops, and products.",
        "f3_title": "Video-Level Metrics", "f3_desc": "Every video comes with detailed sales and engagement data to prove conversion.",
        "f4_title": "Activity Status", "f4_desc": "Monitor creator activity to see who is currently publishing and selling.",
        "f5_title": "Niche Filtering", "f5_desc": "Find creators specifically tailored to your product category or industry.",
        "f6_title": "Agentic Integration", "f6_desc": "Use Creator insights to refine your broader Agentic Commerce ad strategies.",
        "how_heading": "How to Use Creator Library",
        "how_sub": "Validate creators before you collaborate.",
        "s1_title": "Search by Niche", "s1_desc": "Filter our database to find creators operating in your specific target market.",
        "s2_title": "Analyze Sales Data", "s2_desc": "Review their past videos to see exactly how much revenue their content generates.",
        "s3_title": "Identify Top Performers", "s3_desc": "Select the highest-converting creators for your next marketing campaign.",
        "use_heading": "Who Uses Creator Library?",
        "use_sub": "Essential for modern social commerce.",
        "u1_title": "E-commerce Merchants", "u1_ben": "Profitable Partnerships", "u1_desc": "Ensure your influencer marketing budget is spent on creators who drive actual sales.",
        "u2_title": "Media Buyers", "u2_ben": "Creative Analysis", "u2_desc": "Study top-converting organic videos to inspire your paid ad creatives.",
        "u3_title": "Enterprise Brands", "u3_ben": "ROI Validation", "u3_desc": "Bring data-backed transparency to your large-scale influencer campaigns.",
        "use_cta_text": "View Related: Advertiser Library",
        "use_cta_link": "advertiser-library.html",
        "final_heading": "Partner with creators who convert.",
        "final_desc": "Access the Creator Library today and base your marketing on real revenue data.",
        "final_cta_text": "Discover Creators",
        "final_cta_link": "https://app.nexmartshop.ai/sign-up"
    },
    "financial-inclusion.html": {
        "title": "Financial Inclusion - Nexmart",
        "desc": "Track the sales and revenue of your shops in real-time to make data-driven financial decisions.",
        "name": "Financial Inclusion (Sales Tracker)",
        "hero_desc": "Track your shop sales and revenue in real-time. Make data-driven decisions alongside the NexPay Smart Wallet.",
        "cta1_text": "Track Your Sales",
        "cta1_link": "https://app.nexmartshop.ai/solutions/sales-tracker",
        "overview_heading": "Complete Financial Visibility",
        "overview_desc": "Our Sales Tracker provides merchants with unparalleled visibility into their e-commerce performance. Monitor daily metrics, track historical revenue trends, and integrate seamlessly with the NexPay Smart Wallet for total financial control.",
        "cta2_text": "Open NexPay Wallet",
        "cta2_link": "#TODO-NEXPAY-PORTAL",
        "features_heading": "Real-Time Revenue Analytics",
        "features_sub": "Understand your cash flow and growth trajectory.",
        "f1_title": "Live Sales Tracking", "f1_desc": "Monitor the sales and revenue of your TikTok shops in real-time.",
        "f2_title": "Historical Revenue Charts", "f2_desc": "Analyze average daily revenue charts to study long-term business patterns.",
        "f3_title": "Daily Metric Dashboards", "f3_desc": "View granular data for sales today, yesterday, 7 days, 30 days, and total.",
        "f4_title": "NexPay Integration", "f4_desc": "Seamlessly manage payouts and earn rewards through our integrated smart wallet.",
        "f5_title": "Growth Rate Filtering", "f5_desc": "Filter shops by growth rate to identify rapidly scaling opportunities.",
        "f6_title": "One-Click Monitoring", "f6_desc": "Add any product or shop to your dashboard for handsfree daily tracking.",
        "how_heading": "How Financial Inclusion Works",
        "how_sub": "Take control of your commerce data.",
        "s1_title": "Connect Your Shop", "s1_desc": "Add your TikTok shop or product listings to the tracker.",
        "s2_title": "Monitor Dashboards", "s2_desc": "Review daily updates on sales volume, revenue, and product performance.",
        "s3_title": "Manage Finances", "s3_desc": "Utilize NexPay to handle your business capital securely and efficiently.",
        "use_heading": "Who Uses Financial Inclusion?",
        "use_sub": "Built for merchants focused on scale.",
        "u1_title": "E-commerce Merchants", "u1_ben": "Data-Driven Growth", "u1_desc": "Use accurate sales data to optimize inventory and marketing budgets.",
        "u2_title": "Retail Hub Owners", "u2_ben": "Financial Management", "u2_desc": "Track physical and digital sales through a single, unified financial dashboard.",
        "u3_title": "Everyday Consumers", "u3_ben": "Smart Wallet Access", "u3_desc": "Use NexPay to pay instantly, earn rewards, and access exclusive platform offers.",
        "use_cta_text": "View Related: Logistics Node",
        "use_cta_link": "logistics-node.html",
        "final_heading": "Master your e-commerce finances.",
        "final_desc": "Start tracking your sales today and integrate with the Nexmart ecosystem.",
        "final_cta_text": "Track Your Sales",
        "final_cta_link": "https://app.nexmartshop.ai/solutions/sales-tracker"
    },
    "competitor-research.html": {
        "title": "Competitor Research - Nexmart",
        "desc": "Identify your direct competitors, evaluate their strengths, and discover market trends with one click.",
        "name": "Competitor Research",
        "hero_desc": "Identify your direct competitors with one click. Evaluate their strengths, weaknesses, and market positioning.",
        "cta1_text": "Analyze Competitors",
        "cta1_link": "https://app.nexmartshop.ai/solutions/competitor-research",
        "overview_heading": "Uncover Competitive Advantages",
        "overview_desc": "Don't operate in the dark. Our Competitor Research tool provides deep market insights, allowing you to identify direct competitors, find lookalike stores, and benchmark your performance against industry leaders to optimize your strategy.",
        "cta2_text": "Watch Tutorial",
        "cta2_link": "https://app.nexmartshop.ai/videos/competitor-research",
        "features_heading": "Strategic Market Insights",
        "features_sub": "Everything you need to dominate your niche.",
        "f1_title": "One-Click Identification", "f1_desc": "Instantly find out exactly who you are competing against in your specific niche.",
        "f2_title": "Store Lookalikes", "f2_desc": "Discover similar stores built around the same product ideas with a single search.",
        "f3_title": "Competitive Benchmarking", "f3_desc": "Evaluate competitor strengths and weaknesses compared to your own business.",
        "f4_title": "Market Validation", "f4_desc": "Check demand and competition for any product idea before committing resources.",
        "f5_title": "Trend Optimization", "f5_desc": "Use competitor data to optimize your offers, pricing, and marketing strategy.",
        "f6_title": "Seamless Integration", "f6_desc": "Easily pass competitor details to the Advertiser Tracker or Magic AI Search.",
        "how_heading": "How Competitor Research Works",
        "how_sub": "Analyze the market in seconds.",
        "s1_title": "Search Your Niche", "s1_desc": "Input your product category or target keywords into the research tool.",
        "s2_title": "Review Competitors", "s2_desc": "Analyze the list of generated competitors, lookalike stores, and market leaders.",
        "s3_title": "Optimize Strategy", "s3_desc": "Adjust your Nexmartping campaigns based on validated market intelligence.",
        "use_heading": "Who Uses Competitor Research?",
        "use_sub": "Vital for maintaining market dominance.",
        "u1_title": "E-commerce Merchants", "u1_ben": "Market Validation", "u1_desc": "Ensure a product niche isn't overly saturated before launching your store.",
        "u2_title": "Enterprise Brands", "u2_ben": "Strategic Defense", "u2_desc": "Keep a close eye on emerging challengers and industry market share shifts.",
        "u3_title": "Media Buyers", "u3_ben": "Offer Optimization", "u3_desc": "Analyze competitor pricing and bundles to create superior ad offers.",
        "use_cta_text": "View Related: Advertiser Tracker",
        "use_cta_link": "advertiser-tracker.html",
        "final_heading": "Beat the competition with data.",
        "final_desc": "Start analyzing your market today and secure your competitive advantage.",
        "final_cta_text": "Analyze Competitors",
        "final_cta_link": "https://app.nexmartshop.ai/solutions/competitor-research"
    },
    "chrome-extension.html": {
        "title": "Chrome Extension - Nexmart",
        "desc": "A real-time browser companion for product research, sales tracking, and ad insights.",
        "name": "Chrome Extension",
        "hero_desc": "Bring Nexmart's powerful product research, sales tracking, and ad insights directly into your browser workflow.",
        "cta1_text": "Install Extension",
        "cta1_link": "#TODO-CHROME-STORE-LINK",
        "overview_heading": "Agentic Commerce in Your Browser",
        "overview_desc": "The Nexmart Chrome Extension (v1.32) is a lightweight, real-time companion that overlays critical e-commerce data onto your browsing experience. Extract automated insights, analyze products, and monitor sales without ever leaving the page.",
        "cta2_text": "Learn More",
        "cta2_link": "chrome-extension.html",
        "features_heading": "Real-Time Browser Intelligence",
        "features_sub": "Powerful research tools, always one click away.",
        "f1_title": "Real-Time Product Research", "f1_desc": "Analyze products and view revenue estimates directly on external websites.",
        "f2_title": "In-Browser Metrics", "f2_desc": "Access critical sales data and historical trends as an overlay on your screen.",
        "f3_title": "Automated Data Extraction", "f3_desc": "Easily pull product details and competitor data straight into your Nexmart dashboard.",
        "f4_title": "Seamless Workflow", "f4_desc": "Perform comprehensive market research without constantly switching tabs.",
        "f5_title": "Instant Tracking", "f5_desc": "Add newly discovered shops or advertisers to your tracking lists instantly.",
        "f6_title": "Always Updated", "f6_desc": "Powered by Nexmart's constantly refreshing database of millions of products.",
        "how_heading": "How the Extension Works",
        "how_sub": "Supercharge your daily browsing.",
        "s1_title": "Install the Tool", "s1_desc": "Add the Nexmart extension to Chrome and log in to your account.",
        "s2_title": "Browse Normally", "s2_desc": "Navigate social media and e-commerce sites as you usually would.",
        "s3_title": "Access Instant Data", "s3_desc": "Click the extension icon to reveal hidden sales data and product metrics on the page.",
        "use_heading": "Who Uses the Chrome Extension?",
        "use_sub": "The ultimate companion for digital researchers.",
        "u1_title": "E-commerce Merchants", "u1_ben": "Frictionless Research", "u1_desc": "Analyze dropshipping opportunities instantly while browsing supplier sites.",
        "u2_title": "Media Buyers", "u2_ben": "On-the-Fly Analysis", "u2_desc": "Extract data from competitor ads the moment they appear in your social feed.",
        "u3_title": "Everyday Consumers", "u3_ben": "Smarter Shopping", "u3_desc": "Utilize our AI agents to quickly compare prices while shopping online.",
        "use_cta_text": "View Related: Magic AI Search",
        "use_cta_link": "magic-ai-search.html",
        "final_heading": "Upgrade your browser today.",
        "final_desc": "Install the Nexmart Chrome Extension and research products in real-time.",
        "final_cta_text": "Install Extension",
        "final_cta_link": "#TODO-CHROME-STORE-LINK"
    },
    "pre-built-stores.html": {
        "title": "Pre-built Stores - Nexmart",
        "desc": "Instantly generate free, customized Shopify stores pre-loaded with high-converting dropshipping products.",
        "name": "Pre-built Stores",
        "hero_desc": "Utilize AI to instantly generate free, fully customized Shopify stores pre-loaded with winning products.",
        "cta1_text": "Generate Free Store",
        "cta1_link": "https://start.nexmartshop.ai/",
        "overview_heading": "Launch Your Business Instantly",
        "overview_desc": "Skip the technical setup and design headaches. Our Pre-built Stores tool uses AI to automatically generate high-quality Shopify storefronts, integrating seamlessly with Nexmartping winners so you can start selling immediately.",
        "cta2_text": "View Themes",
        "cta2_link": "#TODO-THEMES-GALLERY",
        "features_heading": "Automated Store Creation",
        "features_sub": "Everything you need to launch a professional e-commerce business.",
        "f1_title": "Automated Generation", "f1_desc": "Create a fully functional, customized e-commerce storefront in minutes using AI.",
        "f2_title": "Shopify Integration", "f2_desc": "Built to integrate flawlessly with Shopify's powerful backend infrastructure.",
        "f3_title": "Winning Product Injection", "f3_desc": "Stores come pre-loaded with validated, high-converting products from our database.",
        "f4_title": "Optimized Themes", "f4_desc": "Utilizes professional, conversion-optimized design themes out of the box.",
        "f5_title": "Agentic Ready", "f5_desc": "Fully compatible with Nexmart's Agentic Commerce tools and Tracking Agents.",
        "f6_title": "Free to Start", "f6_desc": "Generate your custom AI Shopify store for free and scale at your own pace.",
        "how_heading": "How Pre-built Stores Work",
        "how_sub": "From idea to live store in minutes.",
        "s1_title": "Select Your Niche", "s1_desc": "Choose your target market or let our AI suggest profitable product categories.",
        "s2_title": "Generate Store", "s2_desc": "Our system automatically builds the Shopify layout and injects the winning products.",
        "s3_title": "Launch and Sell", "s3_desc": "Connect your domain, configure your payment gateway, and start driving traffic.",
        "use_heading": "Who Uses Pre-built Stores?",
        "use_sub": "The perfect launchpad for entrepreneurs.",
        "u1_title": "E-commerce Merchants", "u1_ben": "Rapid Launch", "u1_desc": "Test new product niches instantly without spending days designing a new site.",
        "u2_title": "Everyday Consumers", "u2_ben": "Easy Business Entry", "u2_desc": "Start your first dropshipping business with zero coding or design experience.",
        "u3_title": "Enterprise Brands", "u3_ben": "Micro-Brand Testing", "u3_desc": "Quickly spin up separate storefronts to A/B test new brand concepts.",
        "use_cta_text": "View Related: Theme Detector",
        "use_cta_link": "theme-detector.html",
        "final_heading": "Start your e-commerce journey.",
        "final_desc": "Generate your free, customized AI Shopify store and start selling today.",
        "final_cta_text": "Generate Free Store",
        "final_cta_link": "https://start.nexmartshop.ai/"
    },
    "theme-detector.html": {
        "title": "Theme Detector - Nexmart",
        "desc": "Discover the exact Shopify theme powering any successful competitor's e-commerce store.",
        "name": "Theme Detector",
        "hero_desc": "Discover the exact Shopify theme powering any successful competitor's e-commerce store instantly.",
        "cta1_text": "Detect Theme",
        "cta1_link": "https://app.nexmartshop.ai/free-tools/theme-detector",
        "overview_heading": "Reverse Engineer Success",
        "overview_desc": "Great design drives conversions. Our free Theme Detector tool allows you to analyze any successful Shopify store and instantly identify the exact theme they are using, streamlining your own storefront design and competitive research.",
        "cta2_text": "Try Pre-built Stores",
        "cta2_link": "pre-built-stores.html",
        "features_heading": "Instant Theme Identification",
        "features_sub": "A simple, powerful diagnostic tool for store design.",
        "f1_title": "Shopify Theme Detection", "f1_desc": "Instantly identify both free and premium themes used by Shopify stores.",
        "f2_title": "URL Analysis", "f2_desc": "Simply paste a competitor's URL to extract their public design framework.",
        "f3_title": "Free Tool Access", "f3_desc": "Access this powerful diagnostic utility completely free of charge.",
        "f4_title": "Design Inspiration", "f4_desc": "Find out exactly how market leaders structure their high-converting sites.",
        "f5_title": "Fast Processing", "f5_desc": "Get accurate theme results in seconds without complex manual code inspection.",
        "f6_title": "Ecosystem Integration", "f6_desc": "Use your findings to select the perfect layout for your own Pre-built Store.",
        "how_heading": "How Theme Detector Works",
        "how_sub": "Find the perfect theme in seconds.",
        "s1_title": "Find a Store", "s1_desc": "Identify a highly successful competitor store you admire.",
        "s2_title": "Enter the URL", "s2_desc": "Paste the store's web address into the Theme Detector search bar.",
        "s3_title": "Discover the Theme", "s3_desc": "Instantly view the name of the Shopify theme powering their success.",
        "use_heading": "Who Uses Theme Detector?",
        "use_sub": "Vital for optimizing e-commerce design.",
        "u1_title": "E-commerce Merchants", "u1_ben": "Design Optimization", "u1_desc": "Upgrade your store's conversion rate by utilizing themes proven to work in your niche.",
        "u2_title": "Enterprise Brands", "u2_ben": "Competitive Analysis", "u2_desc": "Monitor exactly what UI/UX frameworks challengers are deploying.",
        "u3_title": "Media Buyers", "u3_ben": "Landing Page Intel", "u3_desc": "Understand the structural design of the landing pages driving the highest ad ROI.",
        "use_cta_text": "View Related: Chrome Extension",
        "use_cta_link": "chrome-extension.html",
        "final_heading": "Build a better storefront.",
        "final_desc": "Identify competitor themes instantly and elevate your e-commerce design.",
        "final_cta_text": "Detect Theme",
        "final_cta_link": "https://app.nexmartshop.ai/free-tools/theme-detector"
    }
}

def generate_pages():
    for filename, data in pages.items():
        with open('product-template.html', 'r', encoding='utf-8') as f:
            soup = BeautifulSoup(f, 'html.parser')

        # Meta
        title = soup.find('title')
        if title: title.string = data['title']
        meta_desc = soup.find('meta', attrs={'name': 'description'})
        if meta_desc: meta_desc['content'] = data['desc']
        
        html_str = str(soup)
        
        replacements = {
            "[Product Name]": data['name'],
            "[Hero Description / Tagline]": data['hero_desc'],
            "[Primary CTA]": data['cta1_text'],
            'href="#"': f'href="{data["cta1_link"]}"', # Quick replacement for the primary CTA button in hero
            
            "[Product Overview Heading]": data['overview_heading'],
            "[Detailed Product Overview Description explaining the core value proposition.]": data['overview_desc'],
            "[Learn More CTA]": data['cta2_text'],
            # The Learn More CTA also has href="#" in the template, we'll replace the first few instances broadly 
            # but more safely, we replace the specific text placeholders.
            
            "[Key Features]": data['features_heading'],
            "[Subtitle explaining why these features matter]": data['features_sub'],
            
            "[Feature 1 Title]": data['f1_title'], "[Feature 1 detailed description emphasizing value.]": data['f1_desc'],
            "[Feature 2 Title]": data['f2_title'], "[Feature 2 detailed description emphasizing value.]": data['f2_desc'],
            "[Feature 3 Title]": data['f3_title'], "[Feature 3 detailed description emphasizing value.]": data['f3_desc'],
            "[Feature 4 Title]": data['f4_title'], "[Feature 4 detailed description emphasizing value.]": data['f4_desc'],
            "[Feature 5 Title]": data['f5_title'], "[Feature 5 detailed description emphasizing value.]": data['f5_desc'],
            "[Feature 6 Title]": data['f6_title'], "[Feature 6 detailed description emphasizing value.]": data['f6_desc'],
            
            "[How It Works]": data['how_heading'],
            "[Step-by-step product workflow explanation]": data['how_sub'],
            
            "[Step 1 Name]": data['s1_title'], "[Step 1 explanation]": data['s1_desc'],
            "[Step 2 Name]": data['s2_title'], "[Step 2 explanation]": data['s2_desc'],
            "[Step 3 Name]": data['s3_title'], "[Step 3 explanation]": data['s3_desc'],
            
            "[Use Cases / Industries]": data['use_heading'],
            "[Explore how different teams use this product]": data['use_sub'],
            
            "[Use Case 1]": data['u1_title'], "[Use Case 1 Benefit]": data['u1_ben'], "[Explanation of how the product solves problems for Use Case 1]": data['u1_desc'],
            "[Use Case 2]": data['u2_title'], "[Use Case 2 Benefit]": data['u2_ben'], "[Explanation of how the product solves problems for Use Case 2]": data['u2_desc'],
            "[Use Case 3]": data['u3_title'], "[Use Case 3 Benefit]": data['u3_ben'], "[Explanation of how the product solves problems for Use Case 3]": data['u3_desc'],
            
            "[View Use Case CTA]": data['use_cta_text'],
            
            "[Ready to get started?]": data['final_heading'],
            "[Final compelling reason to sign up right now]": data['final_desc'],
            "[Final CTA Button]": data['final_cta_text']
        }
        
        for old, new in replacements.items():
            html_str = html_str.replace(old, new)
            
        # Parse again to fix the hrefs safely since simple string replace for href="#" is risky.
        final_soup = BeautifulSoup(html_str, 'html.parser')
        
        # Hero CTA (Primary)
        hero = final_soup.find('section', class_='is-hero')
        if hero:
            hero_btn = hero.find('a', class_='button-wrap')
            if hero_btn: hero_btn['href'] = data['cta1_link']
            
        # Overview CTA (Secondary)
        overview = final_soup.find('section', class_='is-ai')
        if overview:
            ov_btn = overview.find('a', class_='button-wrap')
            if ov_btn: ov_btn['href'] = data['cta2_link']
            
        # Use Case CTA (Related Product)
        tabs = final_soup.find('section', class_='is-tabs')
        if tabs:
            tab_btns = tabs.find_all('a', class_='button-wrap')
            for tb in tab_btns:
                tb['href'] = data['use_cta_link']
                
        # Final CTA Banner
        final_banner = final_soup.find('section', class_='no-padding-bottom')
        if final_banner:
            final_btn = final_banner.find('a', class_='button-wrap')
            if final_btn: final_btn['href'] = data['final_cta_link']
        
        with open(filename, 'w', encoding='utf-8') as out:
            out.write(str(final_soup))

generate_pages()
